# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pmoxbyU7LQXh66lUpzalGK7Me5KK1YW5PDV/l2E5zSk=,iv:Dc74kQb8NDeVz8ldcfpz2NDuuk9yDwx09qiKX+75u2Y=,tag:bTcpBeIX833FomwlG8AbFw==,type:str]
sops:
  age:
    - recipient: age1e8tt5ccxuyn0227n38x7v5za5eqa2f9h2ztw7552gc8g2yx9m34shjc502
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ3BKVXpNc3VGNkMwUVdw
        VC9SNmVZdHlwazd4K0JJOWREa2NZZUUrYmhrClhlV05WdFlVYVRUVXkvdGRrUnNT
        S2tMbm8zWGhRUFBFQjlBYVhOMFZRd2MKLS0tIHRhc1RZditucVgzUERIRHpZUWI1
        K2lIMHk0QmRjc2NnOXJMV2lQQmpwbXMK8W17P/A5o2PvfNKMxI/uEMrPAwq3nUvd
        6Rkk9Lsk4HIhQTPj2TjKJzYD/fdi5w3ffeKNKdhCOk0UZPsbg9vVYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-06T13:29:01Z"
  mac: ENC[AES256_GCM,data:mIzJDhIz4NkX6lVjqMQUkIXwmx/bTlGt5XcUwzPxRb98P4EcRRBJjvjAKmr1dTzcuajb6SDuxGsjeNcVqnYbYMVMLoZt4diLvpm/oShjARr54CGc4LAqZF2bkRhntC5kK7aWIhPp4630EmjcHypD2B2UxFY4ZqSuoV5C9EGjxk0=,iv:g4DuVW3YxEf5JZNLl0aFH3o6y+T8Z+CAgtJuCM3GVm8=,tag:55xuIFOnz38TzR8mCc7MQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
